### ISSUE TITLE
Nový web pro Pyvec

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/zapojse#1]
Toto je sbírka nápadů na pyvec.org. Jednotlivé nápady, kousky informací, a jiné realizovatelné cíle jsou zašktrávací.
Věci hotové nebo přepsané do jednotlivých jiných *issues* jsou zaškrtnuté.

---

@martinbilek z mailu:

> Spíš, teď když nad tím přemýšlím, tak bysme měli pyvec web už hodně zaktualizovat, většina z toho už neni aktuální. Nechce se do toho někomu?
> 
> Do budoucna bych chtěl udělat nějaký facelift pyvec.org stránky, aby byla akčnější a bylo jasnější co pyvec dělá a k čemu je dobrý jak můžou lidi pomoct a že podporujeme konkrétní akce a konkrétní věci, 
> * [x] chtěl bych tam nějaký **success stories** co už jsme dokázali a tak.  (→ https://github.com/pyvec/pyvec.org/issues/36)
> * [x] Statický stránky, ale s nějakým pěkným obsahem.
> 
> * [x] V rámci toho by tam klidně mohla být **placená sekce na loga**, kde přijde Red Hat nebo Kiwi a řekne my vás sponzorujem a za to chceme loga. A sponzoring by byl měsíční příspěvek na účet - dokud posíláš, máš tam logo. Vyjímka by byla Fraga, kde víme že investujou lidi peníze a čas jiným způsobem.

---

@honzajavorek ze Slacku:

Aktuality spíš na blog ne? 
* [x] Ale mělo by tam být co se pořádá.

V podstatě cílem webu by melo byt, ze kdo tam prijde tak:
- [x] pochopi co pyvec je
- [x] cemu pyvec pomaha a o co se nejak zaslouzil
- [x] k cemu muze pyvec byt nekomu kdo chce neco usporadat a jak mu muze pomoct
- [x] proc by mel nekdo sponzorovat pyvec a poslat mu penize

takze by tam mely byt 
* [x] vyzdvizeny veci ktery organizujem a podporujem, 
* [x] vyzdvizeny co uz se odehralo, 
* [x] mel by tam byt nakej prostor pro sponzory a
* [x] jasne viditelny cislo uctu a
* [x] velkej PayPal button 😄 (→ https://github.com/pyvec/pyvec.org/issues/37)

* [x] a minimalne odkazy na success stories lidi, kterym jsme zmenili zivot :heart: (→ https://github.com/pyvec/pyvec.org/issues/36)

* [x] ty stories nebo detaily uz muzou byt jinde, klidne na blogu, ale z pyvec.org by to melo byt nejak odprezentovany(→ https://github.com/pyvec/pyvec.org/issues/36)

* [x] plus tam musi byt administrativni veci
* [x] (kdo je rada, kdo je reditel, …) (→ https://github.com/pyvec/pyvec.org/issues/19)
* [x] plus nejakej press kit s logem na stazeni

* [x] a chtel bych aby to bylo +- co nejvic staticky a samoudrzbovy, abychom na to nemuseli zase 3 roky sahnout :smile:

to jsou moje napady ^^

---

@benabraham tužkou:

![img_20160820_143246677](https://cloud.githubusercontent.com/assets/283441/17831475/ee81091c-66e9-11e6-93b0-88eba2d5a049.jpg)

---

Zmigrováno z [této Trello kartičky](https://trello.com/c/PRlTvMkI/62-novy-web-pro-pyvec).

---

Z dalších komentářů:
* [x] sekce O nás nebo Tým nebo tak něco, viz https://github.com/pyvec/zapojse/issues/1#issuecomment-242139241 (→ https://github.com/pyvec/pyvec.org/issues/22)

**Comment by honzajavorek** [comment]
tak tady bude vznikat ten nový webík: http://pyvec.github.io/pyvec.org/
je na to branch: https://github.com/pyvec/pyvec.org/tree/gh-pages

**Comment by Visgean** [comment]
A nebylo by lepsi hodit tohle info do python.cz/pyvec nebo python.cz/about ? Prijde mi ze je to zbytecne nejednotne....

**Comment by honzajavorek** [comment]
Ale ono to nejednotné trochu má být, protože pyvec je neziskovka a má jiné
cíle a potřeby než komunitní rozcestník.

Ono to bude provázané odkazy a potom je celkem jedno, na jaké doméně to je.

**Comment by benabraham** [comment]
To, co tam **zatím** najdete, je minimální nutná verze. 
Tedy obsah, který tam musí být ze zákona (i když zatím asi ne všechno) + asi pár nastřelenejch bodů.

Pyvec je občanské sdružení, které má/bude mít x aktivit, které podporuje/zastřešuje vč. python.cz atd., ale informace například pro potenciální sponzory patří už na jeho vlastní web. Co pyvec je a není by právě z novýho webu mělo být jasnější.

Budeme pokračovat, vydržte.

**Comment by honzajavorek** [comment]
Důležitý nápad od @zuzejk: Stránka by měla mít sekci O nás nebo Tým nebo tak něco, kde budou ksichtíky lidí (viz http://pyladies.cz/praha_info/ dole nebo http://apiary.io/company#team), kteří za zodpovídají za jednotlivé aktivity a ten, kdo chce s danou aktivitou jednat, tak jim má psát atd.

Tzn. můžeme tam mít velké tlačítko na info@pyvec.org a někde ofiko kdo je v radě atd., ale důležitější často je, že...
- Zuzka je kontaktní osoba za Pražské Pyladies
- Kubík je za Pražské Pyvo
- Logo PyCon CZ s e-mailem info@pycon.cz je za PyCon
- Já jsem za brněnské Pyvo
- Petr býval (už není) za brněnské Pyladies
- Dan by v budoucnu teoreticky byl za Barcamp (nebo bychom naznali, že je to už dost velké, aby to taky mělo logo s vlastním anonymním info emailem)

atd.

**Comment by encukou** [comment]
Teď už se, předpokládám, budou spíš ladit jednotlivosti než dělat velký redesign kde se musí počítat vším. Rozčlenil jsem proto úvodní příspěvek na jednotlivé minicíle. Bude to tak snad uchopitelnější i pro přispěvatele.

@honzajavorek, považuješ-li něco za hotové, můžeš to zaškrtnout? Udělal bych to, ale bojím se že nevím ke kterým bodům máš v hlavě další plány :)

Ostatní bych pak zmigroval po jednom na pyvec.org (a sloučil duplikáty).

**Comment by honzajavorek** [comment]
@encukou Díky! Zaškrtl jsem. Jestli se dobře dívám, v podstatě to jsou asi jen dvě issues, success stories a paypal/darujme.cz button.

Tento komentář https://github.com/pyvec/zapojse/issues/1#issuecomment-242139241 bych přesunul pod... https://github.com/pyvec/pyvec.org/issues/19, https://github.com/pyvec/guide/issues/11, nebo https://github.com/pyvec/python.cz/issues/139 🙄

**Comment by encukou** [comment]
Ten komentář https://github.com/pyvec/zapojse/issues/1#issuecomment-242139241 jsem si zkopíroval pod  pyvec/pyvec.org#19, a pak jsem umazával informace které v té issue už jsou, až mi zbyl jen zastaralý seznam konkrétních rolí :)

Tak jsem jen do úvodního příspěvku pyvec/pyvec.org#19 dal odkaz sem.

**Comment by encukou** [comment]
Nový pyvec.org žije, tuhle „vykopávací“ diskusi uzavírám. Díky!
